//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TreinoEstagio.Dados
{
    using System;
    using System.Collections.Generic;
    
    public partial class Funcionario
    {
        public int codfuncionario { get; set; }
        public string nome { get; set; }
        public Nullable<System.DateTime> datanasc { get; set; }
        public Nullable<int> codfuncao { get; set; }
    
        public virtual Funcao1 Funcao1 { get; set; }
    }
}
